### ISSUE TITLE
Suggestion to Add MoA

### ISSUE THREAD

**Issue by fuvty** [Zefan-Cai/Awesome-LLM-KV-Cache#1]
Hi, thank you for creating such a valuable list of recent advancements in KV-Cache and long-context LLMs. It is incredibly helpful! I would like to kindly recommend our work, [MoA (Mixture-of-Sparse-Attention)](https://github.com/thu-nics/MoA), which creates a pipeline to search for optimal sparsity for different attention heads and lengths. I believe it could be a valuable addition to the list and benefit the community. 
Thank you for your consideration! Hope we could discuss more on this topic :)

**Comment by Zefan-Cai** [comment]
Please raise a PR for this paper.
